### PR TITLE
Add Janus RTP crash files.

### PR DESCRIPTION
**Pull request by atoppi**
Add the files that crashed Janus while fuzzing the RTP parsers.

The RTP parsers that have been tested are:
- vp8
- vp9
- h264

### CODE REVIEW

**Comment by ibc** [comment]
Are those files codec payloads? If so, may be they should be placed in #1?

**Comment by ibc** [comment]
I'm just thinking about whether the `reports` folder makes sense or not. I mean, I understand it's supposed to hold files that have generated a crash in an implementation. However, does the `reports` folder contain valid RTP, RTCP, STUN, or codec payload "packets"? If so, IMHO they should be placed in the `corpora` folder, am I wrong?

**Comment by atoppi** [comment]
Hi Iñaki,
We have not implemented different fuzzing targets for specific codec payloads, we just let the fuzzer do its mutations on the corpus.

IMHO the `reports` folder should not contain valid packets by definition. If an implementation is crashing with a valid pattern, that is not something that should be shared on this repository but a simple bug in that specific implementation.

In other words, the report files in this PR do not contain valid payloads.

**Comment by atoppi** [comment]
I mean, the sense of the `reports` folder is that if some developer did an error in the implementation and the fuzzer discovered a pattern that triggers that error, maybe some other developer may have done the same error and so the crash file will be useful to easily identify the bug.

**Comment by ibc** [comment]
Yeah, clear. Makes sense. I just (wrongly) understood that the files in this PR were valid RTP packets or codec payloads.

**Pull request merged**
